spring:
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: validate
    show-sql: false

  config:
    import: optional:file:.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    placeholders:
      admin_email: ${ADMIN_EMAIL}
      admin_password: ${ADMIN_PASSWORD}

  mercadopago:
    access-token: ${MP_ACCESS_TOKEN}
    webhook-secret: ${MP_WEBHOOK_SECRET}
    notification-url: ${MP_NOTIFICATION_URL}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: 100
        limit-refresh-period: 60s
        timeout-duration: 0
        register-health-indicator: true

    instances:
      public-api:
            base-config: default
            limit-for-period: 50
            limit-refresh-period: 60s

      create-resource:
            base-config: default
            limit-for-period: 10
            limit-refresh-period: 60s

      critical:
            base-config: default
            limit-for-period: 5
            limit-refresh-period: 60s